version: "3.8"

services:
  backend:
    container_name: market_data_notification
    build:
      context: .
      target: dev
      secrets:
        - source: ssh_private_key
          mode: 0600
    working_dir: /app
    env_file: .env
    command: poetry run python3 main.py
    depends_on:
      - redis
      - chrome
    ports:
      - "8080:8080"
    volumes:
      - ./src:/app/src
    environment:
      ENV: dev
  redis:
    container_name: redis
    build:
      context: .
      dockerfile: Dockerfile-redis
    volumes:
      - redis_data:/data
    ports:
      - 6379:6379
  chrome:
    # https://github.com/seleniumhq-community/docker-seleniarm
    image: seleniarm/standalone-chromium:114.0-20230615
    container_name: chrome
#    shm_size: 2gb
    ports:
      - "4444:4444"
      - "5900:5900"
      - "7900:7900"
#    volumes:
#      - /dev/shm

volumes:
  redis_data:

secrets:
  ssh_private_key:
    file: secret/id_rsa