version: "3.8"

services:
  backend:
    container_name: market_data_notification.com_test
    build:
      context: .
      target: test
    working_dir: /app
    command: poetry run pytest
    depends_on:
      - redis
    volumes:
      - ./:/app
  redis:
    container_name: redis
    image: redis:7.0.7
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"

volumes:
  redis_data: