version: "3.8"

services:
  backend:
    container_name: market_data_notification
    build:
      context: .
      target: dev
      secrets:
        - source: ssh_private_key
          mode: 0600
      args:
        MARKET_DATA_API_TAG: 0.7.1
    working_dir: /app
    env_file: .env
    command: poetry run python3 main.py
    depends_on:
      - redis
    ports:
      - "8080:8080"
    volumes:
      - ./src:/app/src
    environment:
      ENV: dev
  redis:
    container_name: redis
    build:
      context: .
      dockerfile: Dockerfile-redis
    volumes:
      - redis_data:/data
    ports:
      - 6379:6379

volumes:
  redis_data:

secrets:
  ssh_private_key:
    file: secret/id_rsa