version: "3.8"

services:
  backend:
    container_name: market_data_notification.com_test
    build:
      context: .
      target: test
      secrets:
        - source: ssh_private_key
          mode: 0600
    working_dir: /app
    env_file: .env.test
    command: poetry run pytest
    depends_on:
      - redis
    volumes:
      - ./:/app
  redis:
    container_name: redis
    image: redis:7.0.7
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"

volumes:
  redis_data:

secrets:
  ssh_private_key:
    file: secret/id_rsa