name: Test and build
on:
  push:
    branches:
      - feature/*
      - master
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: false
        default: 'info'
        type: choice
        options:
        - info
        - warning
        - debug
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run tests with docker compose
        run: |
          docker-compose -f docker-compose.test.yml up
  build:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          # Can't use self-defined environment variables for some reason
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_BUILD_DEPLOY_TOKEN }}
      - name: Build image
        id: build_image
        uses: docker/build-push-action@v3
        with:
          push: false
          target: release
          tags: ghcr.io/${{ github.repository_owner }}/market_data_notification:${{ github.sha }}
          cache-from: type=registry,ref=ghcr.io/${{ github.repository_owner }}/market_data_notification:buildcache
          cache-to: type=registry,ref=ghcr.io/${{ github.repository_owner }}/market_data_notification:buildcache,mode=max
  notify_unsuccessful:
    runs-on: ubuntu-latest
    needs: [test, build]
    if: ${{ failure() }}
    env:
      TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
    steps:
      - name: Send telegram notification
        run: |
          now=$(date +%Y-%m-%dT%H:%M:%S)
          text=$(echo "\[Github action\] Market data notification backend Test and build failed at $now. Workflow: $GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID" | sed 's~[[:blank:]]~%20~g')
          curl "https://api.telegram.org/bot${TELEGRAM_TOKEN}/sendMessage?chat_id=${TELEGRAM_CHAT_ID}&text=$text"
